server:
  port: 8093
spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.70.128:9300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10 #10s拉取一次服务列表
  instance:
    lease-renewal-interval-in-seconds: 5 #每隔5s发送一次心跳
    lease-expiration-duration-in-seconds: 15 #10秒不发送就过期