server:
  port: 8098
spring:
  application:
    name: cart-server
  redis:
    host: 127.0.0.1
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10 #拉取服务时间
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
leyou:
  jwt:
    pubKeyPath: D:\\ideaProject\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN